### ISSUE TITLE
Transfer vi QR Code or any other offline way

### ISSUE THREAD

**Issue by magdesign** [vogonwann/splitcat#18]
I like your little tool. Wondering if you are interested in implementing some transfer methods which work without internet.

One idea is to transfer via QR code, even if it is slow, see here:

https://github.com/tony-xlh/QRTransfer
(has a good working demo)

https://github.com/bradparks/txqr___transfer_data_using_qr_code

https://github.com/mohankumarelec/Airgapped-QR-code-Transfer

**Comment by vogonwann** [comment]
Thank you for the compliments and this great idea. I'll try to implement it as soon as possible.

**Comment by magdesign** [comment]
😍

**Comment by magdesign** [comment]
just tested your release with 2 android devices, but it seems to endlessly scanning the same qr code again and again... maybe i am doing something wrong, but it feels like there is a bug..

**Comment by vogonwann** [comment]
> just tested your release with 2 android devices, but it seems to endlessly scanning the same qr code again and again... maybe i am doing something wrong, but it feels like there is a bug..

QR code should be same until devices IP changes, just select another file and scan again.

**Comment by magdesign** [comment]
here it scans, goes black, enables camera again to scan, goes black, enables camera to scan and so on...
debloated Android 14 device.

**Comment by vogonwann** [comment]
can you check if storage permissions are enabled for the application?
