### ISSUE TITLE
signing key changed?

### ISSUE THREAD

**Issue by IzzySoft** [vogonwann/splitcat#22]
What happened to your signing key? The update yesterday was rejected as it no longer matched:

```
Binary files /web/ftp/repo/fdroid/repo/lol.janjic.splitcat_2017.apk and /web/ftp/repo/fdroid/repo/lol.janjic.splitcat_0.1.16.apk differ
! repo/lol.janjic.splitcat_2017.apk declares sensitive permission(s): android.permission.CAMERA
2024-11-05 19:44:56,469 WARNING: "lol.janjic.splitcat_2017.apk" is signed by a key that is not allowed:
a67aca0367fcef38f745a24185cb2071b45dfe42009814fbffe2381a049d99cb
```

Very unlucky combination also that you forgot to increase `versionCode` – so it kicked out the previous release even.

Previous key was:

```
Signer #1 certificate DN: CN=Ivan Janjić, OU=Unknown, O=janjique, L=Smederevo, ST=Serbia, C=RS
Signer #1 certificate SHA-256 digest: 7859304de0b566da26bee1992e9921f221a6bdc2993b5ac783cda8a97ef8bad7
Signer #1 certificate SHA-1 digest: 67c5f1981bcdd623b45af01b5652a0d4f075ae22
Signer #1 certificate MD5 digest: b6e7a20f731622f25278de43c97d0c35
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
```

But the last APK was signed with

```
Signer #1 certificate DN: CN=Ivan Janjic, OU=Unknown, O=janjique, L=Smederevo, ST=Serbia, C=RS
Signer #1 certificate SHA-256 digest: a67aca0367fcef38f745a24185cb2071b45dfe42009814fbffe2381a049d99cb
Signer #1 certificate SHA-1 digest: 6fa2c98fabc7f9b7d606663e56049bb04a2fe90c
Signer #1 certificate MD5 digest: eece2fa805b9228a0f9ccb32685882af
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
```

So for now, updates at IzzyOnDroid are disabled until we can solve this riddle. I'll try to re-establish the last version (which now was overwritten) until then.

**Comment by IzzySoft** [comment]
Wait, what is that? Previous release (v0.1.15) was signed with:

```
Number of signers: 1
Signer #1 certificate DN: CN=Ivan Janjić, OU=Unknown, O=janjique, L=Smederevo, ST=Serbia, C=RS
Signer #1 certificate SHA-256 digest: 7859304de0b566da26bee1992e9921f221a6bdc2993b5ac783cda8a97ef8bad7
Signer #1 certificate SHA-1 digest: 67c5f1981bcdd623b45af01b5652a0d4f075ae22
Signer #1 certificate MD5 digest: b6e7a20f731622f25278de43c97d0c35
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
```

Are you generating a new key with each release? That does not work, nobody can update that way. Signing is a security feature, to prevent unauthorized updates (e.g. provided by a malicious party). So updates with a different signing key are not accepted by any device (unless one rooted it and disabled signature verification).

**Comment by vogonwann** [comment]
I changed singing key because I wanted to release the app on Play Store and the previous key was not acceptable by Google. Now signing is the part of release building process and will not change anymore. Sorry for the inconvenience.

**Comment by IzzySoft** [comment]
You changed it 3 times? All 3 keys are RSA-2048, so what reason did Google give for rejecting the first 2? And how can we confirm it's really you (your commits are not signed, there's no alternative channel of contact established, and you are the sole contributor here), see [How to keep your key safe and what measures to take for the event of loss?](https://f-droid.org/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html#lessons-learned-2-how-to-keep-your-key-safe-and-what-measures-to-take-for-the-event-of-loss) Did you keep the original key, so we can use that for verification?

**Comment by IzzySoft** [comment]
OK, successfully verified now, so the currently latest key (sha256: a67aca0367fcef38f745a24185cb2071b45dfe42009814fbffe2381a049d99cb) was marked as accepted and updates have been re-enabled. Please check the above link for good measures. I highly recommend to

* make a good backup of your current key and put it to a safe place
* start signing your commits (always good to have a fallback!)

Thanks!

**Comment by vogonwann** [comment]
Thanks for everything! I'll be more careful in the future.
