### ISSUE TITLE
Compression option

### ISSUE THREAD

**Issue by laki2021** [vogonwann/splitcat#5]
App is great, looking nice. Do you plan  to implement compression and encryption with spliting process, in the future, as an option?

**Comment by vogonwann** [comment]
Great idea. Will look into it!

**Comment by vogonwann** [comment]
When you say encryption do you think of archive with password or really encrypted data?

**Comment by laki2021** [comment]
>Archive with a password to start with because it's easier and faster, and it meets some basic needs when sending files over the net. And later for more demanding users  full encryption why not. But for the beginning archive with a password I think.


>When you say encryption do you think of archive with password or really encrypted data?

**Comment by vogonwann** [comment]
Compression and password protection are in the main now. I will close this issue
